version: '3'
services:

  nginx:
    image: nginx:latest
    container_name: epesi-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: epesi/php
    container_name: epesi-php
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:5.6
    container_name: epesi-db
    restart: on-failure
    ports:
      - '33062:3306'
    environment:
      MYSQL_ROOT_PASSWORD: epesi
      MYSQL_DATABASE: epesi
      MYSQL_USER: epesi
      MYSQL_PASSWORD: epesi
    networks:
      - app-network


networks:
  app-network:
    driver: bridge